### ISSUE TITLE
Merging master branch into main branch

### ISSUE THREAD

**Issue by Rahma-AlWadhahi** [Varun270/6Companies30Days#1]
### Description
This is to address the issue discussed in discord. @Varun270, please attach relevant information/screenshots.

The problem happened because the branch `main` and the branch `master` do not share the same history log. To solve this problem, we will create a separate branch which will contain both the history from `main` branch and then merge `master` branch to it.
Error message while merging - 
<img width="389" alt="Em1" src="https://user-images.githubusercontent.com/75975268/148647693-35ca20ab-5be2-4623-ac4f-e2d9d6b69b3a.png">

<img width="929" alt="Em2" src="https://user-images.githubusercontent.com/75975268/148647743-7183c8da-ce4c-4cc2-93bd-ba003ffde78f.png">

**Comment by Rahma-AlWadhahi** [comment]
I am trying to push the changes to the repository but this is what I am getting. It seems that I don't have permission.
Could you please give permission to push the changes @Varun270 ?
You can add me as a collaborator [here](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-user-account/managing-access-to-your-personal-repositories/inviting-collaborators-to-a-personal-repository)

<img width="872" alt="Screen Shot 2022-01-08 at 18 26 49" src="https://user-images.githubusercontent.com/61970868/148647981-e10e0678-c4df-4190-842f-358150fa7f89.png">

**Comment by Varun270** [comment]
> I am trying to push the changes to the repository but this is what I am getting. It seems that I don't have permission. Could you please give permission to push the changes @Varun270 ? You can add me as a collaborator [here](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-user-account/managing-access-to-your-personal-repositories/inviting-collaborators-to-a-personal-repository)
> 
> <img alt="Screen Shot 2022-01-08 at 18 26 49" width="872" src="https://user-images.githubusercontent.com/61970868/148647981-e10e0678-c4df-4190-842f-358150fa7f89.png">

Done
